version: '2'

services:
  ds-ml-server:
    image: time-range:latest
    command: python3 main.py
    container_name: time-range
    restart: unless-stopped
    ports:
       - 8555:8080
    environment:
      - USER=DEMO_USER
      - PASSW=DEMO_PASSWORD
    logging:
      driver: "json-file"
      options:
          max-size: "1200m"
